package ru.starashchuk.currency.exchange.util;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import ru.starashchuk.currency.exchange.controller.exception.DatabaseException;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

@Component
public class DatabaseInitializer {
    private DatabaseSource databaseSource;

    @Autowired
    public DatabaseInitializer(DatabaseSource databaseSource) {
        this.databaseSource = databaseSource;
        init();
    }

    private static final String CREATE_DATABASES_REQUEST = """
            CREATE TABLE IF NOT EXISTS currencies(
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code varchar(3) NOT NULL,
                full_name varchar NOT NULL,
                sign varchar NOT NULL
            );
            CREATE TABLE IF NOT EXISTS exchange_rates(
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                base_currency_id INTEGER REFERENCES currencies (id),
                target_currency_id INTEGER REFERENCES currencies (id),
                rate DECIMAL(20, 6) NOT NULL check(rate > 0)
            );
            CREATE UNIQUE INDEX IF NOT EXISTS idx_code ON currencies(code);
            """;
    private static final String DATABASE_EXCEPTION_MESSAGE = "Error on the database side";

    public void init() {
        try (Connection connection = databaseSource.getDbConnection();
             PreparedStatement ps = connection.prepareStatement(CREATE_DATABASES_REQUEST)) {
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new DatabaseException(DATABASE_EXCEPTION_MESSAGE);
        }
    }
}
